input_directory : "/mnt/n/AudioWalks/H3-VC/2025-6-20_to_7-31/"
database_path : "/mnt/n/AudioWalks/H3-VC/2025-6-20_to_7-31/audiomoth.db"

# Audio parameters
sample_rate: 48000
file_duration_sec: 900

# Display parameters
width-px : 1000
height-px : 300
border-px : 0
dpi : 100

# Spectrogram parameters
n_fft : 2048
hop_length : 256
n_mels : 128

# Global contrast normalization range
global_min : -40
global_max : 40

# Acoustic indices configuration - MAAD AAI INDICES
acoustic_indices:
  temporal:
    chunk_duration_sec: 4.5
    # MAAD temporal activity index (AAI temporal)
    maad_temporal_activity:
      processor: maad_temporal_activity
      params: {}
    
    # Keep existing temporal indices for comparison
    temporal_entropy:
      processor: temporal_entropy
      params: {}
      
    temporal_activity:
      processor: temporal_activity
      params: {}
        
    temporal_median:
      processor: temporal_median
      params: {}
      
  spectral:
    chunk_duration_sec: 4.5
    
    # MAAD spectral activity index (AAI spectral)
    maad_spectral_activity:
      processor: maad_spectral_activity
      params: {}
    
    # MAAD spectral activity for Eastern Froglet frequency range
    maad_spectral_activity_eastern_froglet_2500-3500:
      processor: maad_spectral_activity
      params:
        freq_min: 2500
        freq_max: 3500
    
    # Keep existing Eastern Froglet BAI for comparison
    eastern_froglet_bai_2500-3500:
      processor: bioacoustics_index
      params:
        freq_min: 2500
        freq_max: 3500
    
    # Standard complexity analysis for baseline comparison
    acoustic_complexity_index:
      processor: acoustic_complexity_index
      params: {}
    
    # Standard entropy analyses
    spectral_entropy:
      processor: spectral_entropy
      params: {}
      
    frequency_entropy:
      processor: frequency_entropy
      params: {}
