input_directory : "/mnt/n/AudioWalks/H3-VC/test/"
database_path : "/mnt/n/AudioWalks/H3-VC/test/audiomoth.db"

# Audio parameters
sample_rate: 48000
file_duration_sec: 900

# Display parameters
width-px : 1000
height-px : 300
border-px : 0
dpi : 100

# Spectrogram parameters
n_fft : 2048
hop_length : 256
n_mels : 128

# Global contrast normalization range
global_min : -40
global_max : 40

# Acoustic indices configuration - WORKING INDICES ONLY
acoustic_indices:
  temporal:
    chunk_duration_sec: 4.5
    # Standard temporal indices (known working)
    temporal_entropy:
      processor: temporal_entropy
      params: {}
      
    temporal_activity:
      processor: temporal_activity
      params: {}
        
    temporal_median:
      processor: temporal_median
      params: {}
      
  spectral:
    chunk_duration_sec: 4.5
    # Standard spectral indices (known working)
    
    # Standard complexity analysis
    acoustic_complexity_index:
      processor: acoustic_complexity_index
      params: {}
    
    # Standard bioacoustic index
    standard_bai_500-2000:
      processor: bioacoustics_index
      params:
        freq_min: 500
        freq_max: 2000
    
    # Standard soundscape analysis
    standard_soundscape_500-2000:
      processor: soundscape_index
      params:
        bioacoustic_freq_min: 500
        bioacoustic_freq_max: 2000
        anthropogenic_freq_min: 0
        anthropogenic_freq_max: 500
    
    # Standard entropy analyses
    spectral_entropy:
      processor: spectral_entropy
      params: {}
      
    frequency_entropy:
      processor: frequency_entropy
      params: {}