input_directory : "/mnt/n/AudioWalks/H3-VC/2025-6-20_to_7-31/"
database_path : "/mnt/n/AudioWalks/H3-VC/2025-6-20_to_7-31/audiomoth.db"

# Audio parameters
sample_rate: 48000
file_duration_sec: 900

# Acoustic indices configuration - Temporal Median only
acoustic_indices:
  temporal:
    chunk_duration_sec: 4.5
    temporal_median:
      processor: temporal_median
      params: {}