input_directory : "/mnt/n/AudioMoth/2025-Set-MacquarieUni/"
database_path : "/mnt/n/AudioMoth/2025-Set-MacquarieUni/audiomoth.db"

# Audio parameters
sample_rate: 48000
file_duration_sec: 600  # Macquarie Uni AudioMoth recordings are 10 minutes

# Display parameters
width-px : 1000
height-px : 300
border-px : 0
dpi : 100

# Spectrogram parameters
n_fft : 2048
hop_length : 256
n_mels : 128

# Global contrast normalization range
global_min : -40
global_max : 40

# Acoustic indices configuration - STANDARD INDICES ONLY
acoustic_indices:
  temporal:
    chunk_duration_sec: 4.5
    # Standard temporal indices (names match existing database)
    temporal_entropy:
      processor: temporal_entropy
      params: {}

    temporal_activity:
      processor: temporal_activity
      params: {}

    temporal_median:
      processor: temporal_median
      params: {}

  spectral:
    chunk_duration_sec: 4.5
    # Standard spectral indices (names match existing database)

    # Standard complexity analysis
    acoustic_complexity_index:
      processor: acoustic_complexity_index
      params: {}

    # Standard bioacoustic index (matches existing database: standard_bai_500-2000)
    standard_bai_500-2000:
      processor: bioacoustics_index
      params:
        freq_min: 500
        freq_max: 2000

    # Standard soundscape analysis (matches existing database: standard_soundscape_500-2000)
    standard_soundscape_500-2000:
      processor: soundscape_index
      params:
        bioacoustic_freq_min: 500
        bioacoustic_freq_max: 2000
        anthropogenic_freq_min: 0
        anthropogenic_freq_max: 500

    # Standard entropy analyses
    spectral_entropy:
      processor: spectral_entropy
      params: {}

    frequency_entropy:
      processor: frequency_entropy
      params: {}

# Weather integration
weather:
  enabled: true
  cache_directory: ".weather_cache"
  api_provider: "open-meteo"

  variables:
    - temperature_2m
    - relative_humidity_2m
    - precipitation
    - wind_speed_10m
    - weather_code
    - cloud_cover
    - pressure_msl

  sunrise_sunset:
    enabled: true
    temporal_labels: true

  temporal:
    resolution: "hourly"
    timezone_handling: "auto"
    interpolation: "nearest"

  sites:
    - name: "Macquarie University"
      latitude: -33.7747
      longitude: 151.1122

  date_range:
    start_date: "2025-09-15"
    end_date: "2025-10-03"

  thresholds:
    high_wind_speed: 15.0
    heavy_precipitation: 5.0
    temperature_range:
      min: 5.0
      max: 35.0
